# Configuration Railway pour Teamify
# Application Next.js avec Pusher

[build]
builder = "nixpacks"

[deploy]
# Commande de démarrage en production - Next.js avec Pusher
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Configuration des environnements
[environments.production]
variables = { NODE_ENV = "production" }

[environments.staging]
variables = { NODE_ENV = "production" }

# Configuration pour le développement local
[environments.development]
variables = { NODE_ENV = "development" }

# Scripts de développement disponibles
[scripts]
# Développement Next.js avec Pusher
dev = "pnpm dev"

# Build de production
build = "pnpm build"

# Démarrage de production
start = "pnpm start"
